onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /sim_system/UUT/Scheduler_Unit/clk
add wave -noupdate /sim_system/UUT/Scheduler_Unit/rst
add wave -noupdate /sim_system/UUT/Scheduler_Unit/BASE_ADDRESS_COST
add wave -noupdate /sim_system/UUT/Scheduler_Unit/BASE_ADDRESS_DMAx
add wave -noupdate /sim_system/UUT/Scheduler_Unit/BASE_ADDRESS_DMEV
add wave -noupdate /sim_system/UUT/Scheduler_Unit/BASE_ADDRESS_INTH
add wave -noupdate /sim_system/UUT/Scheduler_Unit/BASE_ADDRESS_MEMx
add wave -noupdate /sim_system/UUT/Scheduler_Unit/BASE_ADDRESS_MPDR
add wave -noupdate /sim_system/UUT/Scheduler_Unit/BASE_ADDRESS_MPEV
add wave -noupdate /sim_system/UUT/Scheduler_Unit/BASE_ADDRESS_PLNR
add wave -noupdate /sim_system/UUT/Scheduler_Unit/BASE_ADDRESS_TIMR
add wave -noupdate /sim_system/UUT/Scheduler_Unit/BASE_ADDRESS_TRxU
add wave -noupdate /sim_system/UUT/Scheduler_Unit/ERROR
add wave -noupdate /sim_system/UUT/Scheduler_Unit/ERROR_cmb
add wave -noupdate /sim_system/UUT/Scheduler_Unit/ERROR_flg
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_ACK
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_ACK_DMA_Ready
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_ACK_MPDR_Ready
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_ACK_PSU_Done
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_ACK_RBF
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_ACK_RXD
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_ACK_TBE
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_ACK_TIMER
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_ACK_TXD
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_ADD
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_En
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_EXT_RST
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_REQ
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_REQ_DMA_Ready
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_REQ_MPDR_Ready
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_REQ_PSU_Done
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_REQ_RBF
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_REQ_RXD
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_REQ_TBE
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_REQ_TIMER
add wave -noupdate /sim_system/UUT/Scheduler_Unit/INT_REQ_TXD
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_Address
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_Data_in
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_Data_out
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_DIN_Rdy
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_Dot_Redy_CSB
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_Dot_Redy_DCB
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_Dot_Redy_ECB
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_Dot_Redy_IRH
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_Dot_Redy_MCB
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_Dot_Redy_MEM
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_Dot_Redy_PCB
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_Dot_Redy_PLN
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_Dot_Redy_PLNp
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_Dot_Redy_TCB
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_Dot_Redy_TRx
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_OEN
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_SEL_This_CSB
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_SEL_This_DCB
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_SEL_This_ECB
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_SEL_This_IRH
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_SEL_This_MCB
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_SEL_This_MEM
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_SEL_This_PCB
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_SEL_This_PLN
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_SEL_This_PLNp
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_SEL_This_TCB
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_SEL_This_TRx
add wave -noupdate /sim_system/UUT/Scheduler_Unit/MAIN_PORT_WEN
add wave -noupdate /sim_system/UUT/Scheduler_Unit/OFFSET_PLANE
add wave -noupdate /sim_system/UUT/Scheduler_Unit/RISCV_rst
add wave -noupdate /sim_system/UUT/Scheduler_Unit/uPROC_PORT_accept
add wave -noupdate /sim_system/UUT/Scheduler_Unit/uPROC_PORT_Address
add wave -noupdate /sim_system/UUT/Scheduler_Unit/uPROC_PORT_Data_out
add wave -noupdate /sim_system/UUT/Scheduler_Unit/uPROC_PORT_error
add wave -noupdate /sim_system/UUT/Scheduler_Unit/uPROC_PORT_flush
add wave -noupdate /sim_system/UUT/Scheduler_Unit/uPROC_PORT_invalidate
add wave -noupdate /sim_system/UUT/Scheduler_Unit/uPROC_PORT_rd
add wave -noupdate /sim_system/UUT/Scheduler_Unit/uPROC_PORT_valid
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {15150 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {14845 ns} {15845 ns}
