#include "common.h"

//PE 1 1
C_PE_1_1_cnfig.PE_Src		=	MEM;
C_PE_1_1_cnfig.E_Shift_cnt	=	16;
C_PE_1_1_cnfig.FH_Arith	    =	FULL;
C_PE_1_1_cnfig.IFM_NS		=	UNSIGN;
C_PE_1_1_cnfig.WFM_NS		=	UNSIGN;
C_PE_1_1_cnfig.Add_Sel		=	SELF;
C_PE_1_1_cnfig.E_Zpad_max	=	2;
C_PE_1_1_cnfig.E_Kern_max	=	15;
C_PE_1_1_cnfig.E_Colm_max	=	15;
C_PE_1_1_cnfig.E_Chnl_max	=	15;
C_PE_1_1_cnfig.E_Rows_max	=	15;
C_PE_1_1_cnfig.E_Cntr_max	=	15;
C_PE_1_1_cnfig.E_Bank_min	=	0;
C_PE_1_1_cnfig.E_Bank_max	=	3;
C_PE_1_1_cnfig.E_GBnk_min	=	0;
C_PE_1_1_cnfig.E_GBnk_max	=	0;

//PE 1 2
C_PE_1_2_cnfig.PE_Src		=	MEM;
C_PE_1_2_cnfig.E_Shift_cnt	=	16;
C_PE_1_2_cnfig.FH_Arith	    =	FULL;
C_PE_1_2_cnfig.IFM_NS		=	UNSIGN;
C_PE_1_2_cnfig.WFM_NS		=	UNSIGN;
C_PE_1_2_cnfig.Add_Sel		=	SELF;
C_PE_1_2_cnfig.E_Zpad_max	=	2;
C_PE_1_2_cnfig.E_Kern_max	=	15;
C_PE_1_2_cnfig.E_Colm_max	=	15;
C_PE_1_2_cnfig.E_Chnl_max	=	15;
C_PE_1_2_cnfig.E_Rows_max	=	15;
C_PE_1_2_cnfig.E_Cntr_max	=	15;
C_PE_1_2_cnfig.E_Bank_min	=	0;
C_PE_1_2_cnfig.E_Bank_max	=	3;
C_PE_1_2_cnfig.E_GBnk_min	=	1;
C_PE_1_2_cnfig.E_GBnk_max	=	1;

//PE 1 3
C_PE_1_3_cnfig.PE_Src		=	MEM;
C_PE_1_3_cnfig.E_Shift_cnt	=	16;
C_PE_1_3_cnfig.FH_Arith	    =	FULL;
C_PE_1_3_cnfig.IFM_NS		=	UNSIGN;
C_PE_1_3_cnfig.WFM_NS		=	UNSIGN;
C_PE_1_3_cnfig.Add_Sel		=	SELF;
C_PE_1_3_cnfig.E_Zpad_max	=	2;
C_PE_1_3_cnfig.E_Kern_max	=	15;
C_PE_1_3_cnfig.E_Colm_max	=	15;
C_PE_1_3_cnfig.E_Chnl_max	=	15;
C_PE_1_3_cnfig.E_Rows_max	=	15;
C_PE_1_3_cnfig.E_Cntr_max	=	15;
C_PE_1_3_cnfig.E_Bank_min	=	0;
C_PE_1_3_cnfig.E_Bank_max	=	3;
C_PE_1_3_cnfig.E_GBnk_min	=	2;
C_PE_1_3_cnfig.E_GBnk_max	=	2;

//PE 1 4
C_PE_1_4_cnfig.PE_Src		=	MEM;
C_PE_1_4_cnfig.E_Shift_cnt	=	16;
C_PE_1_4_cnfig.FH_Arith	    =	FULL;
C_PE_1_4_cnfig.IFM_NS		=	UNSIGN;
C_PE_1_4_cnfig.WFM_NS		=	UNSIGN;
C_PE_1_4_cnfig.Add_Sel		=	SELF;
C_PE_1_4_cnfig.E_Zpad_max	=	2;
C_PE_1_4_cnfig.E_Kern_max	=	15;
C_PE_1_4_cnfig.E_Colm_max	=	15;
C_PE_1_4_cnfig.E_Chnl_max	=	15;
C_PE_1_4_cnfig.E_Rows_max	=	15;
C_PE_1_4_cnfig.E_Cntr_max	=	15;
C_PE_1_4_cnfig.E_Bank_min	=	0;
C_PE_1_4_cnfig.E_Bank_max	=	3;
C_PE_1_4_cnfig.E_GBnk_min	=	3;
C_PE_1_4_cnfig.E_GBnk_max	=	3;

//PE 2 1
C_PE_2_1_cnfig.PE_Src		=	MEM;
C_PE_2_1_cnfig.E_Shift_cnt	=	16;
C_PE_2_1_cnfig.FH_Arith	    =	FULL;
C_PE_2_1_cnfig.IFM_NS		=	UNSIGN;
C_PE_2_1_cnfig.WFM_NS		=	UNSIGN;
C_PE_2_1_cnfig.Add_Sel		=	SELF;
C_PE_2_1_cnfig.E_Zpad_max	=	2;
C_PE_2_1_cnfig.E_Kern_max	=	15;
C_PE_2_1_cnfig.E_Colm_max	=	15;
C_PE_2_1_cnfig.E_Chnl_max	=	15;
C_PE_2_1_cnfig.E_Rows_max	=	15;
C_PE_2_1_cnfig.E_Cntr_max	=	15;
C_PE_2_1_cnfig.E_Bank_min	=	4;
C_PE_2_1_cnfig.E_Bank_max	=	7;
C_PE_2_1_cnfig.E_GBnk_min	=	0;
C_PE_2_1_cnfig.E_GBnk_max	=	0;

//PE 2 2
C_PE_2_2_cnfig.PE_Src		=	MEM;
C_PE_2_2_cnfig.E_Shift_cnt	=	16;
C_PE_2_2_cnfig.FH_Arith	    =	FULL;
C_PE_2_2_cnfig.IFM_NS		=	UNSIGN;
C_PE_2_2_cnfig.WFM_NS		=	UNSIGN;
C_PE_2_2_cnfig.Add_Sel		=	SELF;
C_PE_2_2_cnfig.E_Zpad_max	=	2;
C_PE_2_2_cnfig.E_Kern_max	=	15;
C_PE_2_2_cnfig.E_Colm_max	=	15;
C_PE_2_2_cnfig.E_Chnl_max	=	15;
C_PE_2_2_cnfig.E_Rows_max	=	15;
C_PE_2_2_cnfig.E_Cntr_max	=	15;
C_PE_2_2_cnfig.E_Bank_min	=	4;
C_PE_2_2_cnfig.E_Bank_max	=	7;
C_PE_2_2_cnfig.E_GBnk_min	=	1;
C_PE_2_2_cnfig.E_GBnk_max	=	1;

//PE 2 3
C_PE_2_3_cnfig.PE_Src		=	MEM;
C_PE_2_3_cnfig.E_Shift_cnt	=	16;
C_PE_2_3_cnfig.FH_Arith	    =	FULL;
C_PE_2_3_cnfig.IFM_NS		=	UNSIGN;
C_PE_2_3_cnfig.WFM_NS		=	UNSIGN;
C_PE_2_3_cnfig.Add_Sel		=	SELF;
C_PE_2_3_cnfig.E_Zpad_max	=	2;
C_PE_2_3_cnfig.E_Kern_max	=	15;
C_PE_2_3_cnfig.E_Colm_max	=	15;
C_PE_2_3_cnfig.E_Chnl_max	=	15;
C_PE_2_3_cnfig.E_Rows_max	=	15;
C_PE_2_3_cnfig.E_Cntr_max	=	15;
C_PE_2_3_cnfig.E_Bank_min	=	4;
C_PE_2_3_cnfig.E_Bank_max	=	7;
C_PE_2_3_cnfig.E_GBnk_min	=	2;
C_PE_2_3_cnfig.E_GBnk_max	=	2;

//PE 2 4
C_PE_2_4_cnfig.PE_Src		=	MEM;
C_PE_2_4_cnfig.E_Shift_cnt	=	16;
C_PE_2_4_cnfig.FH_Arith	    =	FULL;
C_PE_2_4_cnfig.IFM_NS		=	UNSIGN;
C_PE_2_4_cnfig.WFM_NS		=	UNSIGN;
C_PE_2_4_cnfig.Add_Sel		=	SELF;
C_PE_2_4_cnfig.E_Zpad_max	=	2;
C_PE_2_4_cnfig.E_Kern_max	=	15;
C_PE_2_4_cnfig.E_Colm_max	=	15;
C_PE_2_4_cnfig.E_Chnl_max	=	15;
C_PE_2_4_cnfig.E_Rows_max	=	15;
C_PE_2_4_cnfig.E_Cntr_max	=	15;
C_PE_2_4_cnfig.E_Bank_min	=	4;
C_PE_2_4_cnfig.E_Bank_max	=	7;
C_PE_2_4_cnfig.E_GBnk_min	=	3;
C_PE_2_4_cnfig.E_GBnk_max	=	3;

//PE 3 1
C_PE_3_1_cnfig.PE_Src		=	MEM;
C_PE_3_1_cnfig.E_Shift_cnt	=	16;
C_PE_3_1_cnfig.FH_Arith	    =	FULL;
C_PE_3_1_cnfig.IFM_NS		=	UNSIGN;
C_PE_3_1_cnfig.WFM_NS		=	UNSIGN;
C_PE_3_1_cnfig.Add_Sel		=	SELF;
C_PE_3_1_cnfig.E_Zpad_max	=	2;
C_PE_3_1_cnfig.E_Kern_max	=	15;
C_PE_3_1_cnfig.E_Colm_max	=	15;
C_PE_3_1_cnfig.E_Chnl_max	=	15;
C_PE_3_1_cnfig.E_Rows_max	=	15;
C_PE_3_1_cnfig.E_Cntr_max	=	15;
C_PE_3_1_cnfig.E_Bank_min	=	8;
C_PE_3_1_cnfig.E_Bank_max	=	11;
C_PE_3_1_cnfig.E_GBnk_min	=	0;
C_PE_3_1_cnfig.E_GBnk_max	=	0;

//PE 3 2
C_PE_3_2_cnfig.PE_Src		=	MEM;
C_PE_3_2_cnfig.E_Shift_cnt	=	16;
C_PE_3_2_cnfig.FH_Arith	    =	FULL;
C_PE_3_2_cnfig.IFM_NS		=	UNSIGN;
C_PE_3_2_cnfig.WFM_NS		=	UNSIGN;
C_PE_3_2_cnfig.Add_Sel		=	SELF;
C_PE_3_2_cnfig.E_Zpad_max	=	2;
C_PE_3_2_cnfig.E_Kern_max	=	15;
C_PE_3_2_cnfig.E_Colm_max	=	15;
C_PE_3_2_cnfig.E_Chnl_max	=	15;
C_PE_3_2_cnfig.E_Rows_max	=	15;
C_PE_3_2_cnfig.E_Cntr_max	=	15;
C_PE_3_2_cnfig.E_Bank_min	=	8;
C_PE_3_2_cnfig.E_Bank_max	=	11;
C_PE_3_2_cnfig.E_GBnk_min	=	1;
C_PE_3_2_cnfig.E_GBnk_max	=	1;

//PE 3 3
C_PE_3_3_cnfig.PE_Src		=	MEM;
C_PE_3_3_cnfig.E_Shift_cnt	=	16;
C_PE_3_3_cnfig.FH_Arith	    =	FULL;
C_PE_3_3_cnfig.IFM_NS		=	UNSIGN;
C_PE_3_3_cnfig.WFM_NS		=	UNSIGN;
C_PE_3_3_cnfig.Add_Sel		=	SELF;
C_PE_3_3_cnfig.E_Zpad_max	=	2;
C_PE_3_3_cnfig.E_Kern_max	=	15;
C_PE_3_3_cnfig.E_Colm_max	=	15;
C_PE_3_3_cnfig.E_Chnl_max	=	15;
C_PE_3_3_cnfig.E_Rows_max	=	15;
C_PE_3_3_cnfig.E_Cntr_max	=	15;
C_PE_3_3_cnfig.E_Bank_min	=	8;
C_PE_3_3_cnfig.E_Bank_max	=	11;
C_PE_3_3_cnfig.E_GBnk_min	=	2;
C_PE_3_3_cnfig.E_GBnk_max	=	2;

//PE 3 4
C_PE_3_4_cnfig.PE_Src		=	MEM;
C_PE_3_4_cnfig.E_Shift_cnt	=	16;
C_PE_3_4_cnfig.FH_Arith	    =	FULL;
C_PE_3_4_cnfig.IFM_NS		=	UNSIGN;
C_PE_3_4_cnfig.WFM_NS		=	UNSIGN;
C_PE_3_4_cnfig.Add_Sel		=	SELF;
C_PE_3_4_cnfig.E_Zpad_max	=	2;
C_PE_3_4_cnfig.E_Kern_max	=	15;
C_PE_3_4_cnfig.E_Colm_max	=	15;
C_PE_3_4_cnfig.E_Chnl_max	=	15;
C_PE_3_4_cnfig.E_Rows_max	=	15;
C_PE_3_4_cnfig.E_Cntr_max	=	15;
C_PE_3_4_cnfig.E_Bank_min	=	8;
C_PE_3_4_cnfig.E_Bank_max	=	11;
C_PE_3_4_cnfig.E_GBnk_min	=	3;
C_PE_3_4_cnfig.E_GBnk_max	=	3;

//PE 4 1
C_PE_4_1_cnfig.PE_Src		=	MEM;
C_PE_4_1_cnfig.E_Shift_cnt	=	16;
C_PE_4_1_cnfig.FH_Arith	    =	FULL;
C_PE_4_1_cnfig.IFM_NS		=	UNSIGN;
C_PE_4_1_cnfig.WFM_NS		=	UNSIGN;
C_PE_4_1_cnfig.Add_Sel		=	SELF;
C_PE_4_1_cnfig.E_Zpad_max	=	2;
C_PE_4_1_cnfig.E_Kern_max	=	15;
C_PE_4_1_cnfig.E_Colm_max	=	15;
C_PE_4_1_cnfig.E_Chnl_max	=	15;
C_PE_4_1_cnfig.E_Rows_max	=	15;
C_PE_4_1_cnfig.E_Cntr_max	=	15;
C_PE_4_1_cnfig.E_Bank_min	=	12;
C_PE_4_1_cnfig.E_Bank_max	=	15;
C_PE_4_1_cnfig.E_GBnk_min	=	0;
C_PE_4_1_cnfig.E_GBnk_max	=	0;

//PE 4 2
C_PE_4_2_cnfig.PE_Src		=	MEM;
C_PE_4_2_cnfig.E_Shift_cnt	=	16;
C_PE_4_2_cnfig.FH_Arith	    =	FULL;
C_PE_4_2_cnfig.IFM_NS		=	UNSIGN;
C_PE_4_2_cnfig.WFM_NS		=	UNSIGN;
C_PE_4_2_cnfig.Add_Sel		=	SELF;
C_PE_4_2_cnfig.E_Zpad_max	=	2;
C_PE_4_2_cnfig.E_Kern_max	=	15;
C_PE_4_2_cnfig.E_Colm_max	=	15;
C_PE_4_2_cnfig.E_Chnl_max	=	15;
C_PE_4_2_cnfig.E_Rows_max	=	15;
C_PE_4_2_cnfig.E_Cntr_max	=	15;
C_PE_4_2_cnfig.E_Bank_min	=	12;
C_PE_4_2_cnfig.E_Bank_max	=	15;
C_PE_4_2_cnfig.E_GBnk_min	=	1;
C_PE_4_2_cnfig.E_GBnk_max	=	1;

//PE 4 3
C_PE_4_3_cnfig.PE_Src		=	MEM;
C_PE_4_3_cnfig.E_Shift_cnt	=	16;
C_PE_4_3_cnfig.FH_Arith	    =	FULL;
C_PE_4_3_cnfig.IFM_NS		=	UNSIGN;
C_PE_4_3_cnfig.WFM_NS		=	UNSIGN;
C_PE_4_3_cnfig.Add_Sel		=	SELF;
C_PE_4_3_cnfig.E_Zpad_max	=	2;
C_PE_4_3_cnfig.E_Kern_max	=	15;
C_PE_4_3_cnfig.E_Colm_max	=	15;
C_PE_4_3_cnfig.E_Chnl_max	=	15;
C_PE_4_3_cnfig.E_Rows_max	=	15;
C_PE_4_3_cnfig.E_Cntr_max	=	15;
C_PE_4_3_cnfig.E_Bank_min	=	12;
C_PE_4_3_cnfig.E_Bank_max	=	15;
C_PE_4_3_cnfig.E_GBnk_min	=	2;
C_PE_4_3_cnfig.E_GBnk_max	=	2;

//PE 4 4
C_PE_4_4_cnfig.PE_Src		=	MEM;
C_PE_4_4_cnfig.E_Shift_cnt	=	16;
C_PE_4_4_cnfig.FH_Arith	    =	FULL;
C_PE_4_4_cnfig.IFM_NS		=	UNSIGN;
C_PE_4_4_cnfig.WFM_NS		=	UNSIGN;
C_PE_4_4_cnfig.Add_Sel		=	SELF;
C_PE_4_4_cnfig.E_Zpad_max	=	2;
C_PE_4_4_cnfig.E_Kern_max	=	15;
C_PE_4_4_cnfig.E_Colm_max	=	15;
C_PE_4_4_cnfig.E_Chnl_max	=	15;
C_PE_4_4_cnfig.E_Rows_max	=	15;
C_PE_4_4_cnfig.E_Cntr_max	=	15;
C_PE_4_4_cnfig.E_Bank_min	=	12;
C_PE_4_4_cnfig.E_Bank_max	=	15;
C_PE_4_4_cnfig.E_GBnk_min	=	3;
C_PE_4_4_cnfig.E_GBnk_max	=	3;