#include "common.h"

void Load_ACC_CONFIG();
void Initiate_SUU();


int cntr = 0; 

int main()
{
	Load_ACC_CONFIG();
	Initiate_SUU();
	
	while(1)
	{
		cntr
	}
}

void EXT_INT_0_handler()
{
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_1_1_L = cntr;
}

void Load_ACC_CONFIG()
{
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_1_1_H = 1;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_1_1_L = 2;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_1_2_H = 3;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_1_2_L = 4;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_1_3_H = 5;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_1_3_L = 6;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_1_4_H = 7;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_1_4_L = 8;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_2_1_H = 9;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_2_1_L = 10;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_2_2_H = 11;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_2_2_L = 12;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_2_3_H = 13;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_2_3_L = 14;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_2_4_H = 15;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_2_4_L = 16;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_3_1_H = 17;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_3_1_L = 18;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_3_2_H = 19;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_3_2_L = 20;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_3_3_H = 21;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_3_3_L = 22;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_3_4_H = 23;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_3_4_L = 24;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_4_1_H = 25;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_4_1_L = 26;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_4_2_H = 27;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_4_2_L = 28;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_4_3_H = 29;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_4_3_L = 30;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_4_4_H = 31;
	*C_PERIPHERAL_REG_CONFIG_HOLDER_PE_4_4_L = 32;
}

void Initiate_SUU()
{
	for(int r = 1; r <= 4; r++)
	{
		for(int c = 1; c <= 4; c++)
		{
			for(int k = 0; k <= 15; k++)
			{
				*C_PERIPHERAL_REG_SAU_INITIATE_BIAS_VALUE		= 16 * (4*r + c - 5) + k;
				*C_PERIPHERAL_REG_SAU_INITIATE_BIAS_CONTROL		= (1 << C_SAU_Bias_Wen_pos)|(k << C_SAU_Bias_Kernel_Add_pos)
			}
			*C_PERIPHERAL_REG_SAU_INITIATE_ADDRESS_POINT		= 0X0000DEAD
			*C_PERIPHERAL_REG_SAU_INITIATE_ADDRESS_POINT_CNTR	= (2 << C_SUU_Address_Point_Target_Add_pos)|(3 << C_SUU_Address_Point_Unit_Add_pos)|(1 << C_SUU_Address_Point_SA_UAb_pos)|(1 << C_SUU_Address_Point_Base_Wen_pos);
		}
	}
}
